### ISSUE TITLE
Only allow explicit query params

### ISSUE THREAD

**Issue by exophunk** [4dmind/ignore-query-strings#1]
Nice work!

Would it be possible to enhance it in a way to do it the other way around and whitelist only specific query params?
For example our website only really ever uses the following two query params:

`?page=x` --> else pagination breaks
`?live-preview=x` --> else live preview breaks

I'd rather only allow those two and completely ignore all other query params. Because it is also a security risk to cache every possible query parameter? Someone can query your website with a gazillion queryparams like `?random=123`, `?random=124` at it creates and stores a cache file for every of those.

**Comment by Krzemo** [comment]
Yes.
I was also thinking about it.
An update coming soon.

**Comment by Krzemo** [comment]
v2.0 has just been released
You will need to update config file if you have it already installed
